extends: airbnb-base

parserOptions:
    ecmaVersion: 6
    sourceType: script

env:
    mocha: true

rules:
    # This looks better when multiple functions are
    # chained together (unless they are all one-liners)
    arrow-body-style:
        - error
        - always

    # Trailing commas look bad
    comma-dangle: off

    # ES6 provides names where possible
    func-names:
        - error
        - as-needed

    # 'multiline' is the default, but that does not allow us to have just one parameter
    # on a line by itself, so let's just be consistent
    function-paren-newline:
        - error
        - consistent

    # Haven't found a work-around for this yet
    import/no-dynamic-require: off

    # Just because
    indent:
        - error
        - 4

    max-len:
        - error
        - 110

    # Beacuse, I mean, really...
    no-plusplus:
        - error
        - allowForLoopAfterthoughts: true

    # Allow function declarations at the bottom of a file. They are hoisted in ES6.
    no-use-before-define:
        - error
        - functions: false
          variables: true
          classes: true

    # node 4 does not support destructuring
    prefer-destructuring:
        - error
        - array: false
          object: false

    # node 4 does not support rest params
    prefer-rest-params:
        - off