image: node:8

stages:
    - test
    - package
    - publish

test:
    stage: test
    tags:
        - docker-executor
    script:
        - npm install
        - npm test

build_rpm:
    image: node:8-alpine
    stage: package
    tags:
        - docker-executor
    only:
        - /^release-.*/
    script:
        - apk add rpm bash
        - build/buildRpm.sh
    artifacts:
        name: f5-decon-$CI_BUILD_REF
        paths:
            - build/rpmbuild/RPMS/noarch/

pages:
    tags:
        - docker-executor
    stage: publish
    only:
        - develop
    script:
        - node build/generateDocs.js
    artifacts:
        paths:
            - public