image: node:8-alpine

stages:
    - test
    - package

test:
    stage: test
    script:
        - npm install
        - npm test

build_rpm:
    stage: package
    only:
        - /^release-.*/
    script:
        - apk add rpm bash
        - build/buildRpm.sh
