image: $DOCKER_URL/node:12-buster

stages:
    - update
    - atg-shared-checks
    - lint
    - test
    - build
    - docs
    - deploy
    - integration-test
    - teardown

variables:
    TEST_HARNESS_FILE: ${CI_PROJECT_DIR}/harness_facts.json
    ESR_PRODUCT: DO
    ESR_TEST_RUN_ID: ${CI_JOB_ID}
    ESR_TEST_RUN_WEB_URL: ${CI_JOB_URL}
    TEST_REPORTER_OPTIONS: "--reporter mocha-multi-reporters --reporter-options configFile=test/mochaReporterConfig.json"
    TF_DIRECTORY: test/env/terraform
    TF_HTTP_LOCK_METHOD: POST
    TF_HTTP_UNLOCK_METHOD: DELETE
    TF_HTTP_USERNAME: ${CI_REGISTRY_USER}
    TF_HTTP_PASSWORD: ${CI_JOB_TOKEN}
    TF_CLI_ARGS_apply: "-auto-approve"
    TF_CLI_ARGS_destroy: "-auto-approve"
    TF_STATE_URL: "$CI_API_V4_URL/projects/$CI_PROJECT_ID/terraform/state"
    # terraform will try to update state 5(4+1) times every 3 minutes.
    TF_HTTP_RETRY_MAX: 4
    TF_HTTP_RETRY_WAIT_MIN: 3

# This inherits all the jobs defined in the parent template
# Override variables in this project as needed
include:
# adds atg-shared-checks stage and jobs
# adds atg_shared_checks_result job to test stage
  - project: automation-toolchain/atg-shared-templates
    file: security/base.gitlab-ci.yml
    ref: v1.0.6

update_autotool_deps:
  stage: update
  rules:
    - if: '$UPDATE_DEPS =~ /true/i'
  needs: []
  image: $DOCKER_URL/node:14
  variables:
    UPDATE_BRANCH_NAME: update_autotool_deps
  script:
    - . ./scripts/dev/update-do-deps.sh
    - >
      if [ "$AUTOTOOL_DIFF" = "true" ]; then
        git push -f origin ${UPDATE_BRANCH_NAME}
        node ./scripts/dev/createMR.js
      fi
  tags: [cm-official-docker-executor]

lint:
    stage: lint
    needs: []
    tags:
        - cm-official-docker-executor
    script:
        - npm ci --no-optional
        - npm run lint

test_node:4:
    image: $DOCKER_URL/node:4
    stage: test
    needs: []
    tags:
        - cm-official-docker-executor
    script:
        - npm install --global npm@5.10.0
        - npm install --no-optional
        - npm install mocha@5.2.0
        - npm test

test_node:6:
    image: $DOCKER_URL/node:6
    stage: test
    needs: []
    tags:
        - cm-official-docker-executor
    script:
        - npm install --no-optional
        - npm install mocha@6.2.2
        - npm test -- $TEST_REPORTER_OPTIONS
    artifacts:
        when: always
        reports:
            junit: test_report.xml

test_node:8:
    image: $DOCKER_URL/node:8
    stage: test
    needs: []
    tags:
        - cm-official-docker-executor
    script:
        - npm ci
        - npm install mocha@7
        - npm test -- $TEST_REPORTER_OPTIONS
    artifacts:
        when: always
        reports:
            junit: test_report.xml

test_node:latest:
    stage: test
    needs: []
    tags:
        - cm-official-docker-executor
    script:
        - npm ci
        - npm test -- $TEST_REPORTER_OPTIONS
    artifacts:
        when: always
        reports:
            junit: test_report.xml

test-bigiq-ui:
  stage: test
  needs: []
  parallel:
    matrix:
      - BIGIQ_BRANCH: [master/palisade, master/quartz, master/rainier]
  allow_failure: true
  script:
    - git clone --branch $BIGIQ_BRANCH --depth 1 https://gitlab-ci-token:${CI_JOB_TOKEN}@$CI_SERVER_HOST:$CI_SERVER_PORT/bigiq-mgmt/bigiq-mgmt-test
    - cd bigiq-mgmt-test/tools/declarativeOnboardSchemaValidator
    - npm ci
    - cp -r ../../../src/schema/latest/ schema
    - node validateDO_UiSchemaTest.js > output
    - cat output
    - 'grep -q "Total Failures :  0" output'

coverage:
  image: $DOCKER_URL/node:lts
  stage: test
  needs: []
  tags:
      - cm-official-docker-executor
  script:
        - PUBLIC_DIR='./public'
        - mkdir -p ${PUBLIC_DIR}
        - COVERAGE_DOCS=${PUBLIC_DIR}/coverage-docs
        - mkdir -p ${COVERAGE_DOCS}
        ## place code coverage docs under: /coverage-docs ##
        - npm ci
        - npm run coverage
        - cp -R coverage/* ${COVERAGE_DOCS}
  except:
      # For develop, coverage is run in the pages job
      - develop
      - pipelines
  artifacts:
      paths:
        - public

audit:
  image: $DOCKER_URL/node:lts
  needs: []
  stage: test
  allow_failure: true
  tags:
      - cm-official-docker-executor
  script:
      - npm audit

build_rpm:
    image: $DOCKER_URL/node:12
    stage: build
    needs: []
    tags:
        - cm-official-docker-executor
    except:
        - pipelines
    script:
        # setup node environment
        - apt-get update && apt-get install -y rpm --no-install-recommends
        - scripts/build/buildRpm.sh
        # ensure latest copyrights, requires dev dependencies
        - npm ci
        - node node_modules/@f5devcentral/atg-shared-utilities-dev/scripts/dev/write-copyright.js -c -p scripts/dev/copyright.txt
    artifacts:
        name: ${CI_PROJECT_NAME}-${CI_JOB_NAME}-${CI_PIPELINE_IID}
        paths:
            - dist/
        expire_in: 1 week

reactivate_big_iq_license:
    stage: build
    needs: []
    rules:
        - if: '$REACTIVATE_BIG_IQ_LICENSE =~ /true/i'
    script:
      - npm ci
      - node scripts/dev/reactivateBigIq.js

create docs:
    image: ${CONTAINTHEDOCS_IMAGE}
    stage: build
    needs: []
    allow_failure: true
    script:
        - if [ "$CI_COMMIT_REF_NAME" = "docs-staging" ] || [ "$CI_COMMIT_REF_NAME" = "docs-latest" ]; then
        -   rm -rf docs/_templates
        - fi
        - make html
        - echo "Checking grammar and style"
        # Runs the grammar check on everything except the /docs/drafts directory
        - vale --glob='*.rst' .
        - echo "Checking links"
        - make linkcheck
    tags:
        - cm-official-docker-executor
    artifacts:
        expire_in: 1 week
        name: sphinx-docs_$CI_COMMIT_SHA
        paths:
            - docs/_build/html

.deploy_common: &deploy_common
    image: $INTEGRATION_DEPLOY_IMAGE
    tags:
      - do-test-docker-executor
    stage: deploy
    timeout: 1 hour
    script:
      - apk update
      # Need to add bash, because included sh doen't support arrays
      # used in build_harness_file.sh script to get IP addresses.
      - apk add bash npm build-base python3 cmake
      - if [[ $PROPERTY_TEST == true ]]; then
      -     export TF_VAR_bigip_count=1
      - else
      -     export TF_VAR_bigip_count=3
      - fi
      - cd "$TF_ROOT"
      - terraform init
      # In case of testing failure, BIGIP will not be destroyed,
      # so before run we need to clean leftovers from last night.
      - terraform destroy
      - terraform apply
      - export BIGIPS_ADDRESSES=$(terraform output --json admin_ip | jq -rc .[])
      - export ADMIN_USERNAME=$(terraform output --json admin_username | jq -rc .)
      - export ADMIN_PASSWORD=$(terraform output --json admin_password | jq -rc .)
      - cd -
      - scripts/dev/build_harness_file.sh > $TEST_HARNESS_FILE
      - npm ci
      - node test/integration/setup.js
    artifacts:
      when: always
      paths:
        - ${TEST_HARNESS_FILE}
      expire_in: 1 day
    retry:
      max: 1
      when: script_failure

deploy_for_this_project:
    rules:
      - if: '$RUN_INTEGRATION_TEST =~ /true/i'
    variables:
      TF_ROOT: '$TF_DIRECTORY/plans/openstack'
      TF_VAR_bigip_image: "$BIGIP_IMAGE"
      TF_VAR_nic_count: "$NIC_COUNT"
    before_script:
      - export TRIM_VERSION="$(echo $BIGIP_IMAGE | cut -d '-' -f 2 | tr '.' -)"
      - export TF_HTTP_ADDRESS="$TF_STATE_URL/openstack-$TRIM_VERSION"
      - export TF_HTTP_LOCK_ADDRESS="$TF_HTTP_ADDRESS/lock"
      - export TF_HTTP_UNLOCK_ADDRESS=$TF_HTTP_LOCK_ADDRESS
      - echo using RPM from our pipeline
      - export RPM_PACKAGE=$(ls ${CI_PROJECT_DIR}/dist/*.rpm)
    <<: *deploy_common
    needs:
      - job: build_rpm
        artifacts: true

deploy_for_other_project:
    rules:
      - if: '$TRIGGER_INTEGRATION_TEST =~ /true/i'
    variables:
      TF_ROOT: "$TF_DIRECTORY/plans/openstack"
      TF_VAR_bigip_image: "$BIGIP_IMAGE"
      TF_VAR_nic_count: "$NIC_COUNT"
    before_script:
      - export TRIM_VERSION="$(echo $BIGIP_IMAGE | cut -d '-' -f 2 | tr '.' -)"
      - export TF_HTTP_ADDRESS="$TF_STATE_URL/openstack-$TRIM_VERSION"
      - export TF_HTTP_LOCK_ADDRESS="$TF_HTTP_ADDRESS/lock"
      - export TF_HTTP_UNLOCK_ADDRESS=$TF_HTTP_LOCK_ADDRESS
      - echo using RPM from cross-project pipeline
      - export RPM_PACKAGE=$(ls ${UPSTREAM_RPM_PATH}/*.rpm)
    <<: *deploy_common
    needs:
        - project: "$UPSTREAM_PROJECT_PATH"
          job: "$UPSTREAM_JOB"
          ref: "$UPSTREAM_REF"
          artifacts: true

integration-test:
    tags:
        - do-test-docker-executor
    rules:
      - if: '$RUN_INTEGRATION_TEST =~ /true/i'
      - if: '$TRIGGER_INTEGRATION_TEST =~ /true/i'
    stage: integration-test
    timeout: 3 hours
    before_script:
        - apt-get update
        - apt-get install -y jq
        - export ESR_TEST_TYPE=integration
        - export ESR_PRODUCT_VERSION=$(node -e "console.log(require('./package.json').version)" | cut -d '-' -f1)
        - export ESR_BIG_IP_VERSION=$(echo $BIGIP_IMAGE | cut -d '-' -f 2)
        - export GIT_SSL_NO_VERIFY=1
        - echo BIGIP_VERSION $ESR_BIG_IP_VERSION
        - npm install --no-optional
    script:
        - if [[ $PROPERTY_TEST == true ]]; then
        -     export DO_HOST=$(cat ${TEST_HARNESS_FILE} | jq -r '.[0].admin_ip')
        -     export DO_USERNAME=$(cat ${TEST_HARNESS_FILE} | jq -r '.[0].f5_rest_user.username')
        -     export DO_PASSWORD=$(cat ${TEST_HARNESS_FILE} | jq -r '.[0].f5_rest_user.password')
        -     npm run property -- $TEST_REPORTER_OPTIONS
        - else
        -     npm run integration -- $TEST_REPORTER_OPTIONS
        - fi
    after_script:
        - apt-get install -y expect
        - scripts/dev/collectRemoteIntegrationTestLogs.sh ${TEST_HARNESS_FILE}
    artifacts:
        name: f5-declarative-onboarding-$CI_BUILD_REF
        when: always
        paths:
            - test/logs
        reports:
            junit: test_report.xml
        expire_in: 1 week

.teardown_common: &teardown_common
    image: $INTEGRATION_DEPLOY_IMAGE
    tags:
      - do-test-docker-executor
    stage: teardown
    before_script:
      # terraform doesn't support '.' in backend address.
      - export TRIM_VERSION="$(echo $BIGIP_IMAGE | cut -d '-' -f 2 | tr '.' -)"
      - export TF_HTTP_ADDRESS="$TF_STATE_URL/openstack-$TRIM_VERSION"
    script:
      - cd $TF_DIRECTORY/plans/openstack
      - terraform init
      - terraform destroy
    retry:
      max: 1
      when: script_failure

teardown_for_this_project:
    rules:
      - if: '$SKIP_TEARDOWN =~ /true/i'
        when: never
      - if: '$RUN_INTEGRATION_TEST =~ /true/i'
        when: always
      - when: never
    needs:
        - job: deploy_for_this_project
        - job: integration-test
    <<: *teardown_common

teardown_for_other_project:
    rules:
      - if: '$SKIP_TEARDOWN =~ /true/i'
        when: never
      - if: '$TRIGGER_INTEGRATION_TEST =~ /true/i'
        when: always
      - when: never
    needs:
        - job: deploy_for_other_project
        - job: integration-test
    <<: *teardown_common

# Deploy docs to Pages for review
# Docs are staged on this projects pages site
pages:
    stage: docs
    allow_failure: true
    environment:
        name: review
        url: https://${CI_PROJECT_NAMESPACE}.${PAGES_DOMAIN}/${CI_PROJECT_NAME}/
    tags:
        - cm-official-docker-executor
    needs:
        - create docs
    script:
        # create public directory
        - PUBLIC_DIR='./public'
        - mkdir -p ${PUBLIC_DIR}
        # place index.html in public dir
        - cp docs/index.html ${PUBLIC_DIR}/index.html
        ## place public facing docs under: /public-docs ##
        - PUBLIC_DOCS=${PUBLIC_DIR}/public-docs
        - mkdir -p ${PUBLIC_DOCS}
        - cp -R docs/_build/html/* ${PUBLIC_DOCS}
        ## place code coverage docs under: /coverage-docs ##
        - npm install
        - npm run coverage
        - COVERAGE_DOCS=${PUBLIC_DIR}/coverage-docs
        - mkdir -p ${COVERAGE_DOCS}
        - cp -R coverage/* ${COVERAGE_DOCS}
        ## place code contribution docs (includes presentation) under: /contribute-docs ##
        - CONTRIBUTE_DOCS=${PUBLIC_DIR}/contribute-docs
        - CONTRIBUTE_DIR=contributing
        # install presentation site dependencies
        - cd ${CONTRIBUTE_DIR} && npm install && cd ..
        - mkdir -p ${CONTRIBUTE_DOCS}
        - cp -R ${CONTRIBUTE_DIR}/* ${CONTRIBUTE_DOCS}
        - BASE_URL_FOR_LINKS=${CI_PROJECT_URL}/tree/${CI_COMMIT_REF_NAME}/${CONTRIBUTE_DIR}/
        - README=${CONTRIBUTE_DOCS}/README.md
        # make absolute URL(s) for relative URL(s) outside current directory '../'
        - sed -i -E 's/\[.*\]\(\.\./&SED_TEMP/' ${README} && sed -i "s|..SED_TEMP|${BASE_URL_FOR_LINKS}..|" ${README}
    artifacts:
        paths:
            - public
    only:
        - develop
        - doc-release-branch
        - joes-do-wip

publish docs to production:
    image: ${CONTAINTHEDOCS_IMAGE}
    stage: docs
    environment:
        name: production
        url: https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest
    only:
        # Currently will only deploy to clouddocs.f5.com on commits to doc-publish
        # fill in desired release branch name and uncomment to add deployment from a branch
        - docs-latest@automation-toolchain/f5-declarative-onboarding
    tags:
        - cm-official-docker-executor
    needs:
        - create docs
    script:
        # Publish docs to clouddocs.f5.com (live site).
        - publish-product-docs-to-prod extensions/f5-declarative-onboarding/latest
        - aws s3 cp versions.json s3://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/versions.json
        # create invalidation to clear cloudfront cache
        - aws cloudfront create-invalidation --distribution-id $AWS_DIST --paths /products/extensions/f5-declarative-onboarding
