image: node:8

stages:
    - test
    - package

test:
    stage: test
    tags:
        - docker-executor
    script:
        - npm install
        - npm test

build_rpm:
    image: node:8-alpine
    stage: package
    tags:
        - docker-executor
    script:
        - apk add rpm bash
        - build/buildRpm.sh
    artifacts:
        name: f5-decon-$CI_BUILD_REF
        paths:
            - build/rpmBuild/RPMS/
