image: node:8

stages:
    - test
    - build
    - functional test
    - post build
    - publish

test:
    stage: test
    tags:
        - docker-executor
    script:
        - npm install
        - npm run lint
        - npm test

build rpm:
    image: node:8-alpine
    stage: build
    except:
        - tags
    tags:
        - docker-executor
    script:
        - apk add rpm bash
        - build/buildRpm.sh
    artifacts:
        name: ${CI_PROJECT_NAME}-${CI_JOB_NAME}-${CI_PIPELINE_IID}
        paths:
            - build/rpmbuild/RPMS/noarch/
        expire_in: 1 week

functional test:
    image: centos
    stage: functional test
    tags:
        - docker-executor
    only:
        - schedules
    script:
        # set location of DO RPM package
        - export RPM_PACKAGE=$(ls build/rpmbuild/RPMS/noarch/*.rpm)
        # pull auto-vio prm package
        - curl -u "${ARTIFACTORY_USERNAME}:${ARTIFACTORY_PASSWORD}" -O "${ARTIFACTORY_AUTO_VIO}/${AUTO_VIO_RPM}"
        # test.js can import auto-vio with /var/rpm/auto-vio/vio-lib.js
        - curl -sL https://rpm.nodesource.com/setup_8.x | bash -
        - yum install -y nodejs
        - yum install -y "${AUTO_VIO_RPM}"
        - npm install
        - npm run functional

build asg:
    image: docker:latest
    stage: post build
    except:
        - tags
    tags:
        - docker-executor
    dependencies:
        - build rpm
    script:
        - IMAGE_NAME=f5-do-container
        - ORGANIZATION_NAME=f5devcentral
        - TARGET=$(ls build/rpmbuild/RPMS/noarch/*.rpm)
        # TAG is VERSION-RELEASE. Use awk to remove everything else
        - IMAGE_TAG=$(echo $(basename $TARGET) | awk -F- -v PROJECT_NAME=${CI_PROJECT_NAME}- '{sub(PROJECT_NAME, ""); sub(".noarch.rpm", ""); print}')
        - if [[ ${CI_COMMIT_REF_NAME} == 'master' ]]; then
        -     IMAGE_TAG=$(echo $IMAGE_TAG | grep -o "^[^-]\+")
        - elif [[ ${CI_COMMIT_REF_NAME} != 'develop' ]]; then
        -     IMAGE_TAG=$CI_COMMIT_REF_NAME
        - fi
        - docker build -f build/Dockerfile.asg -t ${ORGANIZATION_NAME}/${IMAGE_NAME}:${IMAGE_TAG} --build-arg TARGET=$TARGET .
        - docker save ${ORGANIZATION_NAME}/${IMAGE_NAME}:${IMAGE_TAG} | gzip -c > dist/${ORGANIZATION_NAME}-${IMAGE_NAME}-${IMAGE_TAG}.tar.gz
    artifacts:
        name: ${CI_PROJECT_NAME}-${CI_JOB_NAME}-${CI_PIPELINE_IID}
        paths:
            - dist/*.tar.gz
        expire_in: 1 week

create postman collection:
    stage: post build
    except:
        - tags
    tags:
        - docker-executor
    script:
        - node build/generatePostmanCollection.js
    artifacts:
        name: ${CI_PROJECT_NAME}-${CI_JOB_NAME}-${CI_PIPELINE_IID}
        paths:
            - dist/do.examples.collection.json
        expire_in: 1 week

publish to artifactory:
    stage: publish
    only:
        - tags
    tags:
        - docker-executor
    dependencies:
        - build rpm
    script:
        - RPM_FILE=$(ls build/rpmbuild/RPMS/noarch/*.rpm)
        - RPM_NAME=$(basename $RPM_FILE)
        - >-
            UPLOAD_RESULT=$(curl -H "Authorization: Bearer ${ARTIFACTORY_BEARER_TOKEN}" -X PUT --data-binary @${RPM_NAME}
            ${ARTIFACTORY_BASE_URL}/f5-declarative-onboarding-rpm/${RPM_NAME})
        - echo $UPLOAD_RESULT
        - if [[ "$UPLOAD_RESULT" == *errors* ]]; then echo error during upload; exit 1; fi

create docs:
    image: ${CONTAINTHEDOCS_IMAGE}
    stage: post build
    script:
        - make html
        - echo "Checking grammar and style"
        # Runs the grammar check on everything except the /docs/drafts directory
        - vale --glob='*.rst' .
        - echo "Checking links"
        - make linkcheck
    tags:
        - cm-official-docker-executor
    artifacts:
        expire_in: 1 week
        name: sphinx-docs_$CI_COMMIT_SHA
        paths:
            - docs/_build/html

# Deploy docs to Pages for review
# Docs are staged on this projects pages site
pages:
    stage: publish
    environment:
        name: review
        url: https://${CI_PROJECT_NAMESPACE}.${PAGES_DOMAIN}/${CI_PROJECT_NAME}/
    tags:
        - cm-official-docker-executor
    dependencies:
        - create docs
    script:
        - mkdir -p ./public
        - cp -R docs/_build/html/* ./public
    artifacts:
        paths:
            - public
    only:
        - branches

publish docs to staging:
    image: ${CONTAINTHEDOCS_IMAGE}
    stage: publish
    environment:
        name: staging
        url: https://clouddocs.f5networks.net/products/extensions/f5-declarative-onboarding/latest
    tags:
        - cm-official-docker-executor
    only:
        - doc-staging@cloudsolutions/f5-declarative-onboarding
    dependencies:
        - create docs
    script:
        - aws s3 sync docs/_build/html s3://clouddocs.f5networks.net/products/extensions/f5-declarative-onboarding/latest
        # create invalidation to clear cloudfront cache
        - aws cloudfront create-invalidation --distribution-id $AWS_DIST --paths /products/extensions/f5-declarative-onboarding/latest/

publish docs to production:
    image: ${CONTAINTHEDOCS_IMAGE}
    stage: publish
    environment:
        name: production
        url: https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest
    only:
        # Currently will only deploy to clouddocs.f5.com on commits to doc-publish
        # fill in desired release branch name and uncomment to add deployment from a branch
        - doc-publish@cloudsolutions/f5-declarative-onboarding
    tags:
        - cm-official-docker-executor
    dependencies:
        - create docs
    script:
        # Publish docs to clouddocs.f5.com (live site).
        - publish-product-docs-to-prod extensions/f5-declarative-onboarding/latest
        # create invalidation to clear cloudfront cache
        - aws cloudfront create-invalidation --distribution-id $AWS_DIST --paths /products/extensions/f5-declarative-onboarding
