image: node:8

stages:
    - lint
    - test
    - build
    - deploy
    - functional test
    - teardown
    - post build
    - publish

lint:
    image: node:8
    stage: lint
    tags:
        - cm-official-docker-executor
    script:
        - npm ci
        - npm run lint

test_node4:
    image: node:4
    stage: test
    tags:
        - cm-official-docker-executor
    script:
        - npm install --global npm@5.10.0
        - npm install
        - npm install mocha@5.2.0
        - npm test

test_node6:
    image: node:6
    stage: test
    tags:
        - cm-official-docker-executor
    script:
        - npm install
        - npm test

test_node8:
    stage: test
    tags:
        - cm-official-docker-executor
    script:
        - npm ci
        - npm test

# for this job following variables should be defined:
# CICD_AUTH_OS_USERNAME - VIO user
# CICD_AUTH_OS_PASSWORD - VIO password
# CICD_AUTH_OS_PROJECT  - VIO project
deploy bigip:
    image: ${CICD_CONTAINER_DEPLOY}
    stage: deploy
    tags:
        - cm-official-docker-executor
    variables:
        PROJECT_NAME: ${CI_PROJECT_NAME}
        PROJECT_DIR: /root/deploy-projects/${CI_PROJECT_NAME}
        BIGIP_VERSION: 13.1.1.4
        BIGIP_BUILD: 0.0.4
        NUMBER_OF_BIGIP: 3
        DO_LICENSING: 'false'
        DO_PROVISIONING: 'false'
    only:
        - schedules
        - tags
    script:
        - cd /root/cicd-bigip-deploy && make configure &&
            make printvars && cat ${PROJECT_DIR}/project-vars &&
            make setup && ls -als ${PROJECT_DIR} &&
            cp ${PROJECT_DIR}/harness_facts_flat.json ${CI_PROJECT_DIR}/harness_facts_flat.json
        - if [[ $? != 0 ]]; then
        -     echo setup failed
        -     exit 1
        - fi
        - cd ${CI_PROJECT_DIR}
        - export RPM_PACKAGE=$(ls build/rpmbuild/RPMS/noarch/*.rpm)
        - export TEST_HARNESS_FILE=${CI_PROJECT_DIR}/harness_facts_flat.json
        - curl -sL https://rpm.nodesource.com/setup_8.x | bash -
        - yum install -y nodejs
        - npm install
        - node test/functional/setup.js
    artifacts:
        name: ${CI_COMMIT_REF_NAME}_bigip_${BIGIP_BRANCH}.${BIGIP_VERSION}.${BIGIP_BUILD}_harness_info
        paths:
            - ${CI_PROJECT_DIR}/harness_facts_flat.json
        expire_in: 40min

functional test:
    image: centos
    stage: functional test
    tags:
       - cm-official-docker-executor
    only:
        - schedules
        - tags
    script:
       - export TEST_HARNESS_FILE=${CI_PROJECT_DIR}/harness_facts_flat.json
       - curl -sL https://rpm.nodesource.com/setup_8.x | bash -
       - yum install -y nodejs
       - npm install
       - npm run functional

teardown bigip:
    image: ${CICD_CONTAINER_DEPLOY}
    stage: teardown
    tags:
        - cm-official-docker-executor
    variables:
        PROJECT_NAME: ${CI_PROJECT_NAME}
        PROJECT_DIR: /root/deploy-projects/${CI_PROJECT_NAME}
        NUMBER_OF_BIGIP: 3
    script:
      - cd /root/cicd-bigip-deploy && make configure && make teardown
    when: always
    only:
        - schedules
        - tags

build rpm:
    image: node:8-alpine
    stage: build
    tags:
        - cm-official-docker-executor
    script:
        - apk add rpm bash
        - build/buildRpm.sh
    artifacts:
        name: ${CI_PROJECT_NAME}-${CI_JOB_NAME}-${CI_PIPELINE_IID}
        paths:
            - build/rpmbuild/RPMS/noarch/
        expire_in: 1 week

build asg:
    image: docker:latest
    stage: post build
    except:
        - tags
        - schedules
    tags:
        - cm-official-docker-executor
    dependencies:
        - build rpm
    script:
        - IMAGE_NAME=f5-do-container
        - ORGANIZATION_NAME=f5devcentral
        - TARGET=$(ls build/rpmbuild/RPMS/noarch/*.rpm)
        # TAG is VERSION-RELEASE. Use awk to remove everything else
        - IMAGE_TAG=$(echo $(basename $TARGET) | awk -F- -v PROJECT_NAME=${CI_PROJECT_NAME}- '{sub(PROJECT_NAME, ""); sub(".noarch.rpm", ""); print}')
        - if [[ ${CI_COMMIT_REF_NAME} == 'master' ]]; then
        -     IMAGE_TAG=$(echo $IMAGE_TAG | grep -o "^[^-]\+")
        - elif [[ ${CI_COMMIT_REF_NAME} != 'develop' ]]; then
        -     IMAGE_TAG=$CI_COMMIT_REF_NAME
        - fi
        - docker build -f build/Dockerfile.asg -t ${ORGANIZATION_NAME}/${IMAGE_NAME}:${IMAGE_TAG} --build-arg TARGET=$TARGET .
        - docker save ${ORGANIZATION_NAME}/${IMAGE_NAME}:${IMAGE_TAG} | gzip -c > dist/${ORGANIZATION_NAME}-${IMAGE_NAME}-${IMAGE_TAG}.tar.gz
    artifacts:
        name: ${CI_PROJECT_NAME}-${CI_JOB_NAME}-${CI_PIPELINE_IID}
        paths:
            - dist/*.tar.gz
        expire_in: 1 week

create postman collection:
    stage: post build
    except:
        - tags
        - schedules
    tags:
        - cm-official-docker-executor
    script:
        - node build/generatePostmanCollection.js
    artifacts:
        name: ${CI_PROJECT_NAME}-${CI_JOB_NAME}-${CI_PIPELINE_IID}
        paths:
            - dist/do.examples.collection.json
        expire_in: 1 week

publish to artifactory:
    stage: publish
    only:
        - tags
    tags:
        - cm-official-docker-executor
    script:
        # If the tag contains a '-', then get RPM from the build artifact, otherwise, get it from dist
        # since no '-' in the tag means it's s release and should have been committed to dist.
        - if [[ $CI_COMMIT_TAG == *"-"* ]]; then
        -     RPM_FILE=$(ls build/rpmbuild/RPMS/noarch/*.rpm)
        - else
        -     RPM_FILE=$(ls dist/*.rpm)
        - fi
        - RPM_NAME=$(basename $RPM_FILE)
        - >-
            UPLOAD_RESULT=$(curl -H "Authorization: Bearer ${ARTIFACTORY_BEARER_TOKEN}" -X PUT --data-binary @${RPM_FILE}
            ${ARTIFACTORY_BASE_URL}/f5-declarative-onboarding-rpm/${RPM_NAME})
        - echo $UPLOAD_RESULT
        - if [[ "$UPLOAD_RESULT" == *errors* ]]; then echo error during upload; exit 1; fi

create docs:
    image: ${CONTAINTHEDOCS_IMAGE}
    stage: post build
    except:
        - tags
        - schedules
    script:
        - make html
        - echo "Checking grammar and style"
        # Runs the grammar check on everything except the /docs/drafts directory
        - vale --glob='*.rst' .
        - echo "Checking links"
        - make linkcheck
    tags:
        - cm-official-docker-executor
    artifacts:
        expire_in: 1 week
        name: sphinx-docs_$CI_COMMIT_SHA
        paths:
            - docs/_build/html

# Deploy docs to Pages for review
# Docs are staged on this projects pages site
pages:
    stage: publish
    environment:
        name: review
        url: https://${CI_PROJECT_NAMESPACE}.${PAGES_DOMAIN}/${CI_PROJECT_NAME}/
    tags:
        - cm-official-docker-executor
    dependencies:
        - create docs
    script:
        - mkdir -p ./public
        - cp -R docs/_build/html/* ./public
    artifacts:
        paths:
            - public
    only:
        - branches

publish docs to staging:
    image: ${CONTAINTHEDOCS_IMAGE}
    stage: publish
    environment:
        name: staging
        url: https://clouddocs.f5networks.net/products/extensions/f5-declarative-onboarding/latest
    tags:
        - cm-official-docker-executor
    only:
        - doc-staging@cloudsolutions/f5-declarative-onboarding
    dependencies:
        - create docs
    script:
        - aws s3 sync docs/_build/html s3://clouddocs.f5networks.net/products/extensions/f5-declarative-onboarding/latest
        # create invalidation to clear cloudfront cache
        - aws cloudfront create-invalidation --distribution-id $AWS_DIST --paths /products/extensions/f5-declarative-onboarding/latest/

publish docs to production:
    image: ${CONTAINTHEDOCS_IMAGE}
    stage: publish
    environment:
        name: production
        url: https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest
    only:
        # Currently will only deploy to clouddocs.f5.com on commits to doc-publish
        # fill in desired release branch name and uncomment to add deployment from a branch
        - doc-publish@cloudsolutions/f5-declarative-onboarding
    tags:
        - cm-official-docker-executor
    dependencies:
        - create docs
    script:
        # Publish docs to clouddocs.f5.com (live site).
        - publish-product-docs-to-prod extensions/f5-declarative-onboarding/latest
        # create invalidation to clear cloudfront cache
        - aws cloudfront create-invalidation --distribution-id $AWS_DIST --paths /products/extensions/f5-declarative-onboarding
