image: node8

stages:
    - test
    - package

test:
    stage: test
    tags:
        - docker-executor
    script:
        - npm install
        - npm test

build_rpm:
    image: node:8-alpine
    stage: package
    tags:
        - docker-executor
    only:
        - /^release-.*/
    script:
        - apk add rpm bash
        - build/buildRpm.sh
