image: node:8

stages:
    - test
    - build
    - deploy
    - functional test
    - teardown
    - post build
    - publish

test:
    stage: test
    tags:
        - docker-executor
    script:
        - npm install
        - npm run lint
        - npm test

deploy bigip:
    image: ${CICD_CONTAINER_DEPLOY}
    stage: deploy
    tags:
        - cm-official-docker-executor
    variables:
        PROJECT_NAME: ${CI_PROJECT_NAME}
        PROJECT_DIR: /root/deploy-projects/${CI_PROJECT_NAME}
        BIGIP_VERSION: 13.1.1.4
        BIGIP_BUILD: 0.0.4
        NUMBER_OF_BIGIP: 3
        DO_LICENSING: 'false'
        DO_PROVISIONING: 'false'
    artifacts:
        name: ${CI_COMMIT_REF_NAME}_bigip_${BIGIP_BRANCH}.${BIGIP_VERSION}.${BIGIP_BUILD}_harness_info
        paths:
            - ${CI_PROJECT_DIR}/harness_facts_flat.json
        expire_in: 40min
    only:
        - schedules
    script:
        - cd /root/cicd-bigip-deploy && make configure &&
            make printvars && cat ${PROJECT_DIR}/project-vars &&
            make setup && ls -als ${PROJECT_DIR} &&
            cp ${PROJECT_DIR}/harness_facts_flat.json ${CI_PROJECT_DIR}/harness_facts_flat.json
        - cd ${CI_PROJECT_DIR}
        #- export RPM_PACKAGE=$(ls build/rpmbuild/RPMS/noarch/*.rpm)
        - export RPM_PACKAGE=dist/f5-declarative-onboarding-1.3.0-4.noarch.rpm
        - export TEST_HARNESS_FILE=${CI_PROJECT_DIR}/harness_facts_flat.json
        - curl -sL https://rpm.nodesource.com/setup_8.x | bash -
        - yum install -y nodejs
        - npm install
        - node test/functional/setup.js

functional test:
    image: centos
    stage: functional test
    tags:
       - cm-official-docker-executor
    only:
        - schedules
    script:
       - export TEST_HARNESS_FILE=${CI_PROJECT_DIR}/harness_facts_flat.json
       - curl -sL https://rpm.nodesource.com/setup_8.x | bash -
       - yum install -y nodejs
       - npm install
       - npm run functional

teardown bigip:
    image: ${CICD_CONTAINER_DEPLOY}
    stage: teardown
    tags:
        - cm-official-docker-executor
    variables:
        PROJECT_NAME: do-testing
        PROJECT_DIR: /root/deploy-projects/do-testing
    script:
      - cd /root/cicd-bigip-deploy && make configure && make teardown
    when: always 
    only:
        - schedules
